### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by safalabolo** [RobiFag/GRASS_clouds_and_shadows#1]
Hello,
I have encountered the following problem:
running the python script from GRASS 7.4.1 on Windows 10 system, after loading Sentinel-2 bands.
Thanks in advance for your reply.

###########################

C:\Users\safalabolo\Desktop\GRASS_clouds_and_shadows-master\GRASS_clouds_and_shadows-master\i.sentinel.mask\i.sentinel.mask.py -r -t -s -c --overwrite --verbose blue=B02@PERMANENT green=B03@PERMANENT red=B04@PERMANENT nir=B08@PERMANENT nir8a=B8A@PERMANENT swir11=B11@PERMANENT swir12=B12@PERMANENT cloud_mask=cloud shadow_mask=shadow cloud_threshold=50000 shadow_threshold=10000 mtd_file=C:\Users\safalabolo\Desktop\S2A_MSIL2A_20180821T095031_N0208_R079_T33TVE_20180821T134506.SAFE\MTD_MSIL2A.xml
--- The computational region has been temporarily set to image max extent ---
--- Start rescaling bands ---
B02@PERMANENT
B03@PERMANENT
B11@PERMANENT
B08@PERMANENT
B12@PERMANENT
B04@PERMANENT
B8A@PERMANENT
--- The computational region has been reset to the previous one---
--- No temporary files have been deleted ---
Traceback (most recent call last):
  File "C:\Users\safalabolo\Desktop
\GRASS_clouds_and_shadows-master\GRASS_clouds_and_shadows-
master\i.sentinel.mask\i.sentinel.mask.py", line 590, in
<module>
    main()
  File "C:\Users\safalabolo\Desktop
\GRASS_clouds_and_shadows-master\GRASS_clouds_and_shadows-
master\i.sentinel.mask\i.sentinel.mask.py", line 294, in
main
    gscript.message(_(f_bands.values()))
  File
"C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\gettext.py", line
435, in lgettext
    tmsg = self._catalog.get(message, missing)
TypeError: unhashable type: 'list'
(Fri Aug 31 15:04:12 2018) Comando terminato (22 sec)

**Comment by RobiFag** [comment]
Hi,
have you installed i.sentinel.mask using g.extension?
I usually run GRASS GIS on Linux so I don't know exactly how it works on Windows but maybe you have to install the module using the official svn repository.

Moreover, I noticed that you select the wrong metadata file and checked the -c flag to compute only the cloud mask therefore, the output name for the shadow mask and the metadata file are not required (see the manual page for further information).

**Comment by mlennert** [comment]
Looking at the error message, I see you have code such as this (sorry, should have been more attentive earlier):

`gscript.message(_(f_bands.values()))`

I think this is where the problem comes from: you indicate that the message is to be translated by enclosing it in (_(..)). However, the contents of the message is a list (the return value of the values() function). This list does not have a defined value (it depends on the f_bands), and so it is not hashable. This makes handling of translations impossible.

As you want to print the list of map names, these should in any case not be translated, so you could replace that line simply with:

`gscript.message(f_bands.values())`

**Comment by RobiFag** [comment]
Thank you Moritz!
I tested both modules on Windows and I did not get this kind of error anyway if the syntax (_(..)) creates problems I will replace it. Is it better to remove the (_ from all the gscript.message or only from those with this kind of value?

**Comment by safalabolo** [comment]
Hi,
Thank you for your feedback, at this moment it is much appreciated!
I have installed what was requested in GRASS 7.4.1 under SO Windows 10 and I have the following error message:

g.extension -s --verbose extension=i.sentinel url=                              
Downloading precompiled GRASS Addons <i.sentinel>...
Downloading source code for <i.sentinel> from <http://wingrass.fsv.cvut.cz/grass74/x86_64/addons/grass-7.4.0/i.sentinel.zip> which is identified as 'remote_zip' type of source...
Updating addons metadata file...
Manual page for <i.sentinel> updated
ERROR: Unable to read manual page: [Errno 2] No such file or directory: 'C:\\Program Files\\GRASS GIS 7.4.0\\docs\\html\\i.sentinel.html'
(Mon Sep 03 23:37:14 2018) Comando terminato (9 sec)    

In fact, looking for the i.sentinel module I can not find this installed in GRASS.
Thanks in advance for your support.
All the best.

**Comment by rmarzocchi84** [comment]
You have to check the i.sentinel.mask,  i.sentinel.preproc (and i.sentinel.download and i.sentinel.import) commands (_i,sentinel_ command do not exists). 
Anyway, concerning the error, unfortuantely @lucadelu have recently changed the path of the SVN repository. I do not understand the error, but probably it is better for you to ask in the GRASS-user mailing list.

**Comment by ninsbl** [comment]
i.sentinel should work like [r.green.](https://grass.osgeo.org/grass74/manuals/addons/r.green.html) So, your g.extension command is correct.
If you use the s-flag (system wide install) make sure you have admin rights.

On Linux i.sentinel.html gets build and the addon is installed correctly. But I can confirm your issue on Windows and the landing page i.sentinel.html does not get build on the server either.

My guess is that the Makefile lacks " htmldir" in the "default" line as in r.green:

Compare:
https://trac.osgeo.org/grass/browser/grass-addons/grass7/raster/r.green/Makefile
and
https://trac.osgeo.org/grass/browser/grass-addons/grass7/imagery/i.sentinel/Makefile

@lucadelu, @landam or @mlennert will know ...

**Comment by RobiFag** [comment]
Thank you Stefan for the clarification.

@lucadelu, do you take care of it?

**Comment by neteler** [comment]
Yes, "htmldir" should be there. I added that in SVN:

Committed revision 73246.

**Comment by RobiFag** [comment]
Thank you Markus for fixing!!

**Comment by mlennert** [comment]
> I tested both modules on Windows and I did not get this kind of error anyway if the syntax ((..)) creates problems I will replace it. Is it better to remove the ( from all the gscript.message or only from those with this kind of value?

you should use _() only if the content of the message is something that should be translated. This is not the case here for your band names, so you should not use this syntax. It tells the gettext system that there is a string to be translated. This string is then put into the relevant .po files which then can be translated in Transifex. AFAIK, we currently do not provide a mechanism for the translation of addons, but better do things right from the beginning.

**Comment by RobiFag** [comment]
I have just added a new version of both i.sentinel.mask and i.sentinel.preproc in SVN. I fixed this syntax error and added new control check on input and output.
Thank you all for your feedback and suggestions!
